### PR TITLE
Dialog layout

### PR DESCRIPTION
**Pull request by uckelman**
This PR does two things:

1) It calls `setLabelFor()` to associate the label with the search field.
2) It uses `MigLayout` for an improved dialog layout.

Have a look.

### CODE REVIEW

**Comment by Cattlesquat** [comment]
Cool. I might have questions when I go to work on my "next stage" (searching into Traits and keystrokes and stuff), but I can probably just figure it out.

**Comment by Cattlesquat** [comment]
That was the _fourth_ PR into this PR!

**Comment by uckelman** [comment]
Oh hell, I targeted this against the wrong branch.

**Comment by uckelman** [comment]
Sorry about that, it's getting late. I've opened a new PR for you against the correct branch.

**Comment by Cattlesquat** [comment]
Okay, I reverted this one and merged the other. Check it out... hopefully my PR kung fu was strong enough :-)

**Pull request merged**
